-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'DEVELOPER', 'REVIEWER');

-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('OUTSOURCING', 'SI', 'PRODUCT', 'CONSULTING', 'SPECIALIZED_TECH');

-- CreateEnum
CREATE TYPE "SourceType" AS ENUM ('PUBLIC_WEBSITE', 'DIRECTORY', 'LINKEDIN', 'ARTICLE', 'DEMO_DATA');

-- CreateEnum
CREATE TYPE "SummaryType" AS ENUM ('PROFILE_SUMMARY', 'LLM_SUMMARY', 'MANUAL_NOTE');

-- CreateEnum
CREATE TYPE "VendorClassification" AS ENUM ('OUTSOURCING_VENDOR', 'SI_COMPANY', 'PRODUCT_COMPANY', 'CONSULTING_IT_SERVICE', 'SPECIALIZED_TECH_VENDOR');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'DEVELOPER';
